### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by guyleonard** [fmaguire/predict_secretome#1]
Traceback (most recent call last):
  File "secretome_pipe.py", line 105, in <module>
    main(ARGS)
  File "secretome_pipe.py", line 54, in main
    verbose=argv.verbose)
  File "/media/cs02gl/Forseti/hypho_2015_secretome/predict_secretome/predict_secretome/utils.py", line 258, in signalp
    with open(mature_seqs_fp, 'r') as mature_fh:
IOError: [Errno 2] No such file or directory: '/media/cs02gl/Forseti/hypho_2015_secretome/predict_secretome/intermediate_outputs_Neurospora_crassa_OR74A/signalp_mature_seqs.fasta'

**Comment by fmaguire** [comment]
Hmm try running `./dependencies/signalp-4.1/signalp -t euk -f short -m mature.fas INPUT.fasta`

**Comment by guyleonard** [comment]
Sequence limit reached: Max 10000 sequences are allowed

**Comment by fmaguire** [comment]
Todo: pass on error messages from deps

**Comment by fmaguire** [comment]
mostly resolved in refactor

**Comment by mwylerCH** [comment]
Dear author,
quite some years later, but I have a similar issue, I guess:
```
##Checking Depdencies##
signalp is present? True
tmhmm is present? True
targetp is present? True
runWolfPsortSummary is present? True
secretome_pipe.py:35: UserWarning: 

intermediate output dir: /home/mwyler/software/predict_secretome/intermediate_outputs_TEST exists overwriting contents

  warnings.warn('\n\nintermediate output dir: {0} exists '

##Formatting input fasta: /home/mwyler/tempDeNovo/sORF_candidates_AA.fa##
Input fasta formatted: /home/mwyler/software/predict_secretome/intermediate_outputs_TEST/formatted_input.fasta

##Detecing signal peptides##
Search Complete
Compiling accessions with signal peptides
Traceback (most recent call last):
  File "secretome_pipe.py", line 105, in <module>
    main(ARGS)
  File "secretome_pipe.py", line 49, in main
    full_sequences_with_sigpep_fp = utils.signalp(formatted_fasta_fp,
  File "/home/mwyler/software/predict_secretome/predict_secretome/utils.py", line 258, in signalp
    with open(mature_seqs_fp, 'r') as mature_fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mwyler/software/predict_secretome/intermediate_outputs_TEST/signalp_mature_seqs.fasta'

```
Please let me know if you need further indications or a test file.
Many thanks in advance

**Comment by mwylerCH** [comment]
PS: running the signalp version in the dependency works if the file is small
