### ISSUE TITLE
Error when checking dependencies ./test/test.py

### ISSUE THREAD

**Issue by MuthusaravananS** [fmaguire/predict_secretome#4]
when running ./test/test.py showing an error?  The error showed is attached below please help to rectify the same. 

(base) muthu@imuthu:~/predict_secretome-master$ ./test/test.py
..E......E
Stdout:
Please remove '~/targetp-1.1' to run script
.......
======================================================================
ERROR: test_targetp (__main__.TestDependencies)
Test the targetp dependency is installed and works as expected
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/muthu/predict_secretome-master/./test/test.py", line 147, in test_targetp
    shutil.copytree('dependencies/targetp-1.1', home_targetp)
  File "/home/muthu/anaconda3/lib/python3.9/shutil.py", line 568, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/home/muthu/anaconda3/lib/python3.9/shutil.py", line 467, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/home/muthu/anaconda3/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/muthu/targetp-1.1'

======================================================================
ERROR: test_targetp_func (__main__.TestDependencyParsing)
Test that targetp output is correctly parsed by function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/muthu/predict_secretome-master/./test/test.py", line 445, in test_targetp_func
    actual_secreted_accessions = utils.targetp(self.test_fas)
  File "/home/muthu/predict_secretome-master/test/predict_secretome/utils.py", line 436, in targetp
    sys.exit(1)
SystemExit: 1

Stdout:
Please remove '~/targetp-1.1' to run script

----------------------------------------------------------------------
Ran 17 tests in 2.559s

FAILED (errors=2)

**Comment by fmaguire** [comment]
Did you try following the error message and removing the existing `targetp-1.1` folder:

 `rm -r ~/targetp-1.1` before checking the `./test/test.py` again?

**Comment by MuthusaravananS** [comment]
Dear developer, I tried, but getting error message again. 

(base) muthu@imuthu:~/predict_secretome-master$ rm -r ~/targetp-1.1
(base) muthu@imuthu:~/predict_secretome-master$ ./test/test.py
..dependencies/bin/targetp: 292: gawk: not found
dependencies/bin/targetp: 298: gawk: not found
dependencies/bin/targetp: 306: gawk: not found
cat: infile_how: No such file or directory
Cannot read infile_how
Cannot read infile_how
Cannot read infile_how
Cannot read infile_how
Cannot read infile_how
Cannot read infile_how
Cannot read infile_how
Cannot read infile_how
Cannot read infile_how
Cannot read infile_how
dependencies/bin/targetp: 346: gawk: not found
dependencies/bin/targetp: 348: gawk: not found
dependencies/bin/targetp: 360: gawk: not found
dependencies/bin/targetp: 373: gawk: not found
fmt: end of file
apparent state: unit 5 (unnamed)
last format: (80A1)
lately reading sequential formatted external IO
Aborted (core dumped)
dependencies/bin/targetp: 373: gawk: not found
fmt: end of file
apparent state: unit 5 (unnamed)
last format: (80A1)
lately reading sequential formatted external IO
Aborted (core dumped)
dependencies/bin/targetp: 373: gawk: not found
fmt: end of file
apparent state: unit 5 (unnamed)
last format: (80A1)
lately reading sequential formatted external IO
Aborted (core dumped)
dependencies/bin/targetp: 373: gawk: not found
fmt: end of file
apparent state: unit 5 (unnamed)
last format: (80A1)
lately reading sequential formatted external IO
Aborted (core dumped)
dependencies/bin/targetp: 373: gawk: not found
fmt: end of file
apparent state: unit 5 (unnamed)
last format: (80A1)
lately reading sequential formatted external IO
Aborted (core dumped)
dependencies/bin/targetp: 395: gawk: not found
dependencies/bin/targetp: 533: gawk: not found
dependencies/bin/targetp: 548: gawk: not found
F......E
Stdout:
Please remove '~/targetp-1.1' to run script
.......
======================================================================
ERROR: test_targetp_func (__main__.TestDependencyParsing)
Test that targetp output is correctly parsed by function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/muthu/predict_secretome-master/./test/test.py", line 445, in test_targetp_func
    actual_secreted_accessions = utils.targetp(self.test_fas)
  File "/home/muthu/predict_secretome-master/test/predict_secretome/utils.py", line 436, in targetp
    sys.exit(1)
SystemExit: 1

Stdout:
Please remove '~/targetp-1.1' to run script

======================================================================
FAIL: test_targetp (__main__.TestDependencies)
Test the targetp dependency is installed and works as expected
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/muthu/predict_secretome-master/./test/test.py", line 149, in test_targetp
    self.run_dependencies_and_check_output('expected_targetp_output',
  File "/home/muthu/predict_secretome-master/./test/test.py", line 105, in run_dependencies_and_check_output
    self.compare_files(actual_fn, expected_fn)
  File "/home/muthu/predict_secretome-master/./test/test.py", line 29, in compare_files
    self.assertEqual(expected_output, actual_output)
AssertionError: Lists differ: [' \n[103 chars]es:  10\n', 'Cleavage site predictions not inc[1013 chars]0\n'] != [' \n[103 chars]es:  0\n', 'Cleavage site predictions not incl[262 chars]-\n']

First differing element 2:
'Number of query sequences:  10\n'
'Number of query sequences:  0\n'

First list contains 11 additional elements.
First extra element 9:
'R1qual32.paired_(pai   91          0.034  0.951  0.046   S    1\n'

Diff is 1544 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 17 tests in 2.901s

FAILED (failures=1, errors=1)

**Comment by MuthusaravananS** [comment]
i have tried rm -r ~/targetp-1.1 but still getting error

**Comment by fmaguire** [comment]
You need to install gawk on your system.

**Comment by MuthusaravananS** [comment]
Thanks. Its working now after installing gawk using apt
